name: Release

on:
    push:
      branches:
        - main

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: |
            pnpm run lint

      - name: Typecheck
        run: |
            pnpm run typecheck
